{% set name = "microsoft-kiota-http" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_http-{{ version }}.tar.gz
  sha256: 0b40f37c6c158c2e5b2dffa963a7fc342d368c1a64b8cca08631ba19d0ff94a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - microsoft-kiota-abstractions >=1.0.0,<2.0.0
    - httpx >=0.23.0
    - opentelemetry-api >=1.20.0
    - opentelemetry-sdk >=1.20.0

test:
  imports:
    - kiota_http
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-http-python
  summary: Kiota http request adapter implementation for httpx library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-http-python
  doc_url: https://github.com/microsoft/kiota-http-python/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
