{% set name = "microsoft-kiota-http" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_http-{{ version }}.tar.gz
  sha256: 431c5360b8db340312b38d4e104421062ce80d103209e293f31f187a16c36238

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - urllib3 >=2.2.2,<3.0.0
    - python >=3.8
    - microsoft-kiota-abstractions
    - httpx >=0.23,<0.28
    - opentelemetry-api >=1.27.0
    - opentelemetry-sdk >=1.27.0

test:
  imports:
    - kiota_http
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-http-python
  summary: Kiota http request adapter implementation for httpx library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-http-python
  doc_url: https://github.com/microsoft/kiota-http-python/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
