{% set name = "microsoft-kiota-http" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_http-{{ version }}.tar.gz
  sha256: f70ae4cd712ba81253cbff3cb98e80d33bb70e1ff57de39c72eb2b13dd48b47b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - microsoft-kiota-abstractions
    - httpx >=0.23,<0.28
    - opentelemetry-api >=1.27.0
    - opentelemetry-sdk >=1.27.0
    - urllib3 >=2.2.2,<3.0.0

test:
  imports:
    - kiota_http
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/http/httpx
  summary: Kiota http request adapter implementation for httpx library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-python/tree/main/packages/http/httpx
  doc_url: https://github.com/microsoft/kiota-python/blob/main/packages/http/httpx/README.md

extra:
  recipe-maintainers:
    - xylar
