{% set name = "microsoft-kiota-http" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_http-{{ version }}.tar.gz
  sha256: f7318beb014f35b810e028c5d8e5dce4ea53ba574ddae5e84f495024c37177b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - urllib3 >=2.2.2,<3.0.0
    - python >=3.8
    - microsoft-kiota-abstractions
    - httpx >=0.23.0,<0.24.0
    - opentelemetry-api >=1.27.0
    - opentelemetry-sdk >=1.27.0

test:
  imports:
    - kiota_http
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-http-python
  summary: Kiota http request adapter implementation for httpx library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-http-python
  doc_url: https://github.com/microsoft/kiota-http-python/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
